name: .NET Core Desktop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore and build the project
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./path/to/your/project  # Set your working directory

    - name: Build the project
      run: dotnet build --configuration ${{ matrix.configuration }}
      working-directory: ./path/to/your/project

    # Execute unit tests
    - name: Run tests
      run: dotnet test
      working-directory: ./path/to/your/project.Tests
